FROM python:3.11


RUN pip install --upgrade pip
RUN pip install pyspark==3.5.0
RUN pip install findspark


# Install Java
RUN apt-get update && apt-get install -y default-jdk wget  

# Set Java Home
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64